"""empty message

Revision ID: 0eefce73a1c1
Revises: ea954917b4b0
Create Date: 2025-05-06 02:02:27.080984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eefce73a1c1'
down_revision = 'ea954917b4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('diet_type')
        batch_op.drop_column('workout_difficulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_difficulty', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('diet_type', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
