"""Add new models and updates

Revision ID: 8c4b4ede61c7
Revises: 64c406934557
Create Date: 2025-05-05 23:10:42.185440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4b4ede61c7'
down_revision = '64c406934557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('muscle_group', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('equipment_needed', sa.String(length=255), nullable=True),
    sa.Column('contraindications', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('fitness_goal', sa.String(length=50), nullable=False),
    sa.Column('exercises', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakfast_id', sa.Integer(), nullable=True),
    sa.Column('lunch_id', sa.Integer(), nullable=True),
    sa.Column('dinner_id', sa.Integer(), nullable=True),
    sa.Column('snacks', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['breakfast_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['dinner_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['lunch_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_template_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('exercises_completed', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_protein', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allergens', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_proteins', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('disliked_foods', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('workout_experience', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('workout_days_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('workout_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('workout_duration')
        batch_op.drop_column('workout_days_per_week')
        batch_op.drop_column('workout_experience')
        batch_op.drop_column('allergies')
        batch_op.drop_column('disliked_foods')
        batch_op.drop_column('preferred_proteins')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('allergens')
        batch_op.drop_column('primary_protein')

    op.drop_table('workouts')
    op.drop_table('user_meal_plans')
    op.drop_table('workout_templates')
    op.drop_table('exercises')
    # ### end Alembic commands ###
