"""Add last_login and streak_days columns

Revision ID: af95b0b3fed7
Revises: ffaaa14408d0
Create Date: 2025-04-18 10:34:52.628027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af95b0b3fed7'
down_revision = 'ffaaa14408d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('injury_areas', sa.String(length=255), nullable=True),
    sa.Column('limited_movements', sa.String(length=255), nullable=True),
    sa.Column('dietary_restrictions', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('streak_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goals', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goals')
        batch_op.drop_column('availability')
        batch_op.drop_column('target_weight')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('streak_days')
        batch_op.drop_column('last_login')

    op.drop_table('restrictions')
    # ### end Alembic commands ###
