"""empty message

Revision ID: ea954917b4b0
Revises: 8c4b4ede61c7
Create Date: 2025-05-06 01:26:02.731828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea954917b4b0'
down_revision = '8c4b4ede61c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('workout_difficulty', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('workout_difficulty')
        batch_op.drop_column('diet_type')

    # ### end Alembic commands ###
